### ISSUE TITLE
support remote repositories

### ISSUE THREAD

**Issue by akbarnes** [akbarnes/dupver#11]
Methods to be supported
* SFTP
* SSH?
* Cloud storage via rclone

See https://forum.restic.net/t/using-rclone-as-a-restic-backend/548 as argument against native support

**Comment by bluejuniper** [comment]
https://godoc.org/github.com/aws/aws-sdk-go/service/s3 seems to be pretty easy, so stick with this. Only supporting S3 seems to be OK as backblaze now has a compatible API. SFTP/SSH may not be needed assuming that proxy configuration isn't an issue.

**Comment by bluejuniper** [comment]
Only supporting S3 seems to be OK as backblaze now has a compatible API

**Comment by akbarnes** [comment]
No longer needed with distributed repo format, repos can be copied with rclone
