### ISSUE TITLE
decompress archives before deduplicating

### ISSUE THREAD

**Issue by akbarnes** [akbarnes/dupver#19]
Probably the best way to handle this is to convert them to "store only" instead of using DEFLATE while keeping files in the archive

**Comment by akbarnes** [comment]
Probably the best way to handle this is to convert them to "store only" instead of using DEFLATE while keeping files in the archive

**Comment by bluejuniper** [comment]
Actually it's probably necessary to chunk each file in the archive separately to avoid having chunks span files in the archive

**Comment by akbarnes** [comment]
going with conversion to zip store only for simplicity, this avoids having to add a 2nd traversal for the archive contents
